version: '3'

services:
  nginx:
    container_name: nginx
    image: ghcr.io/a224327780/nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ~/work/wwwroot:/data/wwwroot
      - ~/work/wwwlogs:/data/wwwlogs
      - ~/work/nginx/conf/vhost:/usr/local/nginx/conf/vhost
      - "phpsocket:/tmp"
    depends_on:
      - php
    links:
      - php

  php:
    container_name: php
    image: ghcr.io/a224327780/php
    restart: always
    volumes:
      - ~/work/wwwroot:/data/wwwroot
      - ~/work/wwwlogs:/data/wwwlogs
      - "phpsocket:/tmp"

volumes:
  phpsocket:

